thirdparty:
  foo:
    url: https://httpbin.org/get
  bar:
    url: https://httpbin.org/get

process:
  internal:
    expected: 3

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
