server:
  port: 7373
logging:
  level:
    root: info
spring:
  datasource:
    url: jdbc:postgresql://192.168.68.114:5432/shipping_service
    username: temporal
    password: temporal
  hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true
  temporal:
    namespace: default
    connection:
      target: 192.168.68.114:7233
    workers:
      - name: simple-schedule-worker
        task-queue: my-task-queue
    workersAutoDiscovery:
      packages:
        - dev.tt.poc.simpletask
  
