server:
  port: 7272
logging:
  level:
    root: warn
spring:
  datasource:
    url: jdbc:postgresql://192.168.68.114:5432/payment_service
    username: temporal
    password: temporal
  jpa:
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true