server:
  port: 7275
logging:
  level:
    root: info
spring:
  datasource:
    url: jdbc:postgresql://192.168.68.114:5432/order_service
    username: temporal
    password: temporal
  hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true
  temporal:
    namespace: default
    connection:
      target: 192.168.68.114:7233
    workers:
      - name: inventory-service-worker
        task-queue: order-workflow-taskqueue
    workersAutoDiscovery:
      packages:
        - dev.tt.poc.inventory.activity
  rabbitmq:
    host: 192.168.68.114
    port: 5672
    username: guest
    password: guest