server:
  port: 7272
logging:
  level:
    root: info
spring:
  datasource:
    url: jdbc:postgresql://192.168.68.114:5432/payment_service
    username: temporal
    password: temporal
  hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true
  temporal:
    namespace: default
    connection:
      target: 192.168.68.114:7233
    workers:
      - name: payment-service-worker
        task-queue: order-workflow-taskqueue
    workersAutoDiscovery:
      packages:
        - dev.tt.poc.paymentservice.workflow
        - dev.tt.poc.paymentservice.activity